// Test generated by RoostGPT for test ticTacToe using AI Type Open AI and AI Model gpt-4-1106-preview

project_root/
│
├──__tests__/
│  └──src/
│    └──components/
│      └──game-info/
│        └──GameInfo.test.js  // This is where our test cases will go
│
└──src/
   └──components/
     └──game-info/
       └──GameInfo.js

