// Test generated by RoostGPT for test ticTacToe using AI Type Open AI and AI Model gpt-4-1106-preview

import reportWebVitals from "../../src/reportWebVitals";

// Mocking the web-vitals import
jest.mock("web-vitals", () => ({
  getCLS: jest.fn(),
  getFID: jest.fn(),
  getFCP: jest.fn(),
  getLCP: jest.fn(),
  getTTFB: jest.fn(),
}));

describe("reportWebVitals", () => {
  beforeEach(() => {
    // Clear all mocks before each test
    jest.clearAllMocks();
  });

  test("does not report web vitals if onPerfEntry is not provided", () => {
    reportWebVitals();
    expect(require("web-vitals").getCLS).not.toHaveBeenCalled();
    // The rest of the web vitals metrics checks can also be added here similarly
  });

  test("does not report web vitals if onPerfEntry is not a function", () => {
    reportWebVitals({});
    expect(require("web-vitals").getCLS).not.toHaveBeenCalled();
    // The rest of the web vitals metrics checks can also be added here similarly
  });

  test("reports web vitals when onPerfEntry is a function", () => {
    const mockOnPerfEntry = jest.fn();
    reportWebVitals(mockOnPerfEntry);
    // Here you might need to wait for the promises to resolve e.g. with async/await
    // and use a dynamic import mock if the vitals are reported asynchronously.
    expect(mockOnPerfEntry).toHaveBeenCalled();
    // You can add additional checks for specific metrics here.
  });
});
