// Test generated by RoostGPT for test ticTacToe using AI Type Open AI and AI Model gpt-4-1106-preview

import React from 'react';
import { render, screen, fireEvent } from '@testing-library/react';
import Square from '../../../components/square/Square';

describe('Square component', () => {
  
  test('renders Square component', () => {
    render(<Square />);
    const squareButton = screen.getByRole('button');
    expect(squareButton).toBeInTheDocument();
  });

  test('displays value prop', () => {
    const value = 'X';
    render(<Square value={value} />);
    const squareButton = screen.getByRole('button');
    expect(squareButton).toHaveTextContent(value);
  });
  
  test('calls onClick event handler when clicked', () => {
    const onClick = jest.fn();
    render(<Square onClick={onClick} />);
    const squareButton = screen.getByRole('button');
    fireEvent.click(squareButton);
    expect(onClick).toHaveBeenCalled();
  });

});

