// Test generated by RoostGPT for test ticTacToe using AI Type Open AI and AI Model gpt-4-1106-preview

import React from 'react';
import { render, cleanup, fireEvent } from '@testing-library/react';
import Square from '../../src/components/square/Square';

describe('Square Component', () => {
  afterEach(cleanup);

  // Test case 1: Renders the component with default props
  test('renders correctly with default props', () => {
    const { getByRole } = render(<Square />);
    const button = getByRole('button');
    expect(button).toHaveClass('square');
    expect(button).toHaveTextContent('');
  });

  // Test case 2: Handles the onClick event
  test('calls the onClick event handler when clicked', () => {
    const onClick = jest.fn();
    const { getByRole } = render(<Square onClick={onClick} />);
    const button = getByRole('button');
    fireEvent.click(button);
    expect(onClick).toHaveBeenCalled();
  });

  // Additional test cases can be added here as needed

});

