// Test generated by RoostGPT for test ticTacToe using AI Type Open AI and AI Model gpt-4-1106-preview

import React from 'react';
import { render, fireEvent, cleanup } from '@testing-library/react';
import Board from '../../components/board/Board';
import Square from '../../components/square/Square';

// Extend Jest matchers for asserting on DOM nodes
import '@testing-library/jest-dom';

// Clear all DOM elements after each test
afterEach(cleanup);

describe('Board Component', () => {
  test('renders nine Square components', () => {
    const squares = Array(9).fill(null);
    const { getAllByTestId } = render(<Board squares={squares} onClick={() => {}} jumpTo={() => {}} />);
    const squareComponents = getAllByTestId('square');
    expect(squareComponents).toHaveLength(9);
  });

  test('has a restart button that calls jumpTo with 0 when clicked', () => {
    const jumpToMock = jest.fn();
    const { getByTestId } = render(<Board squares={Array(9).fill(null)} onClick={() => {}} jumpTo={jumpToMock} />);
    const restartButton = getByTestId('restart-button');
    fireEvent.click(restartButton);
    expect(jumpToMock).toHaveBeenCalledWith(0);
  });

  test('calls onClick function with the correct index when a square is clicked', () => {
    const onClickMock = jest.fn();
    const squares = Array(9).fill(null);
    const { getAllByTestId } = render(<Board squares={squares} onClick={onClickMock} jumpTo={() => {}} />);
    const squareComponents = getAllByTestId('square');
    fireEvent.click(squareComponents[0]); // Simulate click on the first square
    expect(onClickMock).toHaveBeenCalledWith(0);
  });

  test('each Square component receives the correct value', () => {
    const squares = ['X', 'O', null, 'X', 'O', null, 'X', 'O', null];
    const { getAllByTestId } = render(<Board squares={squares} onClick={() => {}} jumpTo={() => {}} />);
    const squareComponents = getAllByTestId('square');
    expect(squareComponents[0]).toHaveTextContent('X');
    expect(squareComponents[1]).toHaveTextContent('O');
    // ...and so on for the other squares
  });
});

