// Test generated by RoostGPT for test ticTacToe using AI Type Open AI and AI Model gpt-4-1106-preview

import React from 'react';
import { render, screen, fireEvent } from '@testing-library/react';
import '@testing-library/jest-dom';
import Square from '../../../components/square/Square';

describe('Square Component', () => {
  test('renders Square with the correct value', () => {
    const value = 'X';
    render(<Square value={value} onClick={() => {}} />);
    const squareButton = screen.getByRole('button', { name: value });
    expect(squareButton).toHaveTextContent(value);
  });

  test('calls onClick event on click of the Square', () => {
    const onClick = jest.fn();
    render(<Square value="X" onClick={onClick} />);
    const squareButton = screen.getByRole('button', { name: 'X' });
    fireEvent.click(squareButton);
    expect(onClick).toHaveBeenCalled();
  });

  test('Square has the correct className', () => {
    render(<Square value="O" onClick={() => {}} />);
    const squareButton = screen.getByRole('button', { name: 'O' });
    expect(squareButton).toHaveClass('square');
  });

  test('displays empty button when no value is provided', () => {
    render(<Square onClick={() => {}} />);
    const squareButton = screen.getByRole('button');
    expect(squareButton).toBeEmptyDOMElement();
  });
});


