// Test generated by RoostGPT for test reactTesting using AI Type Open AI and AI Model gpt-4-1106-preview


import React from 'react';
import { render, fireEvent } from '@testing-library/react';
import '@testing-library/jest-dom/extend-expect';
import Square from '../../../../src/components/square/Square.js';

describe('Square Component', () => {
  test('renders the button with the provided value', () => {
    const { getByText } = render(<Square value="X" onClick={() => {}} />);
    expect(getByText("X")).toBeInTheDocument();
  });

  test('calls the onClick callback when clicked', () => {
    const onClickMock = jest.fn();
    const { getByText } = render(<Square value="X" onClick={onClickMock} />);
    fireEvent.click(getByText("X"));
    expect(onClickMock).toHaveBeenCalled();
  });

  // Add more test cases as needed...
});

